## release.yml

name: Release
on:
  push:
    tags:
      - "v*"
permissions:
  contents: write
  packages: write
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Sources
        uses: actions/checkout@v4

      - name: Configure Bazel Build
        uses: bazelbuild/setup-bazelisk@v2

      - name: Mount Bazel Cache
        uses: actions/cache@v3.3.2
        with:
          path: |
            ~/.cache/bazel
          key: ${{ runner.os }}-bazel-${{ hashFiles('.bazelversion', '.bazelrc', 'WORKSPACE', 'WORKSPACE.bazel', 'MODULE.bazel', '**/BUILD.bazel') }}
          restore-keys: |
            ${{ runner.os }}-bazel-
          enableCrossOsArchive: true
          fail-on-cache-miss: true

      - name: Build All
        run: bazel build //...

#      - name: Test All
#        run: bazel test //...